### ISSUE TITLE
rb images don't show on permalink

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/tower#45]
immediately after reporting back the user is taken to the permalink page. image is showing up as broken.

![image](https://cloud.githubusercontent.com/assets/6330971/7777743/683b5f14-0093-11e5-873f-f5edce1702d3.png)

**Comment by sergii-tkachenko** [comment]
@mikefantini could you please copy direct link to the RB here?

**Comment by mikefantini** [comment]
@sergii-tkachenko https://www.dosomething.org/reportback/80947?fid=110809

**Comment by mikefantini** [comment]
@sergii-tkachenko also when going back to that campaign i'm seeing it as broken

![image](https://cloud.githubusercontent.com/assets/6330971/7777796/db9d4efe-0093-11e5-9a29-ae25710674d6.png)

**Comment by sergii-tkachenko** [comment]
As I understand this issues consists of 2 items:
- Acamai can't reach this image (https://dosomething-a.akamaihd.net/sites/default/files/styles/480x480/public/uid_2753276-nid_5275-0.jpg?itok=uuvW_Kax) on www.dosomething.org  because it's still looking for it on the old server. * Will be fixed automatically after migation. *
- Actual image (https://www.dosomething.org/sites/default/files/styles/480x480/public/uid_2753276-nid_5275-0.jpg?itok=uuvW_Kax) is not generated on the new server because of shared folder permission. * Fixing it. *

**Comment by sergii-tkachenko** [comment]
Running `sudo chown -R dosomething: .` in shared files folder on drupal-web1
CC @blisteringherb @sheydari-ds

**Comment by sergii-tkachenko** [comment]
It's going to take a while, moved it into `screen` session owned by `dosomething` user.

**Comment by mikefantini** [comment]
just documenting that it's also appearing as broken image in admin screens:

![image](https://cloud.githubusercontent.com/assets/6330971/7778157/d3e24ee6-0096-11e5-85a8-760e35000aad.png)

**Comment by sergii-tkachenko** [comment]
Fixing file permissions helped: https://www.dosomething.org/sites/default/files/styles/480x480/public/uid_2753276-nid_5275-0.jpg?itok=uuvW_Kax

**Comment by sergii-tkachenko** [comment]
Acamai will pick up new images when new DNS records are set. I say this issue is resolved.

**Comment by sheydari-ds** [comment]
Yes, mark it resolved.
